"""permitir venda sem comanda

Revision ID: 1a11ed429abf
Revises: 96b79f1fdbec
Create Date: 2026-09-28 23:10:22.458249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a11ed429abf'
down_revision: Union[str, Sequence[str], None] = '96b79f1fdbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vendas_comanda_id_key'), 'vendas', type_='unique')
    op.drop_constraint(op.f('vendas_comanda_id_fkey'), 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'comanda_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('comanda_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('vendas_comanda_id_fkey'), 'vendas', 'comandas', ['comanda_id'], ['id'])
    op.create_unique_constraint(op.f('vendas_comanda_id_key'), 'vendas', ['comanda_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
