"""add imagem key to produtos

Revision ID: 2b85ce992877
Revises: 5d845b2166e0
Create Date: 2026-09-23 23:12:40.093341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b85ce992877'
down_revision: Union[str, Sequence[str], None] = '5d845b2166e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('imagem_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'imagem_key')
    # ### end Alembic commands ###
