"""criar tabelas de comandas e vendas

Revision ID: 8b98b3bb2d2e
Revises: 2b85ce992877
Create Date: 2026-09-26 19:20:16.146418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b98b3bb2d2e'
down_revision: Union[str, Sequence[str], None] = '2b85ce992877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
