"""criar tabelas de comandas e vendas atualizada

Revision ID: 8f8903f09d18
Revises: d0b85be84d7e
Create Date: 2026-09-26 22:44:17.206838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8903f09d18'
down_revision: Union[str, Sequence[str], None] = 'd0b85be84d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comandas', sa.Column('nome', sa.String(length=90), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comandas', 'nome')
    # ### end Alembic commands ###
