"""criar tabelas de comandas e vendas

Revision ID: 96b79f1fdbec
Revises: 8f8903f09d18
Create Date: 2026-09-26 22:55:55.258469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b79f1fdbec'
down_revision: Union[str, Sequence[str], None] = '8f8903f09d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
